@startgantt
'Week1
[Discussing methods and worklfows] lasts 7 days and is colored in lavendar/LightBlue
[Meeting 1] lasts 1 days and starts after [Discussing methods and worklfows]'s start
'Week2
[agreeing on chosen method and workflow] lasts 1 days and is colored in Coral/Green and starts 0 days after [Discussing methods and worklfows]'s end
[documenting Scrum and CI/CD] lasts 5 days and starts at [agreeing on chosen method and workflow]'s end
[Revision on decision] lasts 1 days and starts after [documenting Scrum and CI/CD]'s end
'Week3 
[forming a backlog and sprint planning] lasts 3 days and starts after [documenting Scrum and CI/CD]'s end
'Week4
[Sprint meeting 1] lasts 1 days and starts after [forming a backlog and sprint planning]'s end
[Sprint backlog tasks] lasts 4 days and starts after [Sprint meeting 1]'s end
'Week5 
[IMPLEMENTATION PHASE] lasts 14 days and starts after [Sprint backlog tasks]'s end


'Week6


@endgantt