@startgantt
project starts 24th September 2025

'24th September - 1st October (Week 1)
[Discussing methods and workflows] lasts 7 days and is colored in Lavender/LightBlue and starts on 24th September 2025
[Meeting 1] happens on 24th September 2025 and is colored in Lavender/Blue
[Customer Meeting] happens on 30th September 2025 and is colored in Lavender/Blue

@endgantt